<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contoso.StorageMachine.Infrastructure\Contoso.StorageMachine.Infrastructure.csproj" />
    <ProjectReference Include="..\Contoso.StorageMachine.Service\Contoso.StorageMachine.Service.csproj" />
  </ItemGroup>

</Project>

