<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contoso.StorageMachine.Application\Contoso.StorageMachine.Application.csproj" />
    <ProjectReference Include="..\Contoso.StorageMachine.Domain\Contoso.StorageMachine.Domain.csproj" />
  </ItemGroup>

</Project>
